services:
  - type: web
    name: learncraft-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://learncraft-backend.onrender.com/api
